In [47]:
%matplotlib inline
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, ElasticNet, Lasso, Ridge

In [48]:
housing = pd.read_fwf("https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data", header = None)

linear = LinearRegression()
regularized = ElasticNet(alpha = 10, l1_ratio = 0.1)

In [37]:
attributes = housing.iloc[:, :-1] #getting all rows and all columns without the last column
attributes.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [38]:
attributes.shape

(506, 13)

In [39]:
labels = housing.iloc[:,-1]
labels.shape

(506,)

In [40]:
labels.unique()

array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,
        18.9,  15. ,  21.7,  20.4,  18.2,  19.9,  23.1,  17.5,  20.2,
        13.6,  19.6,  15.2,  14.5,  15.6,  13.9,  16.6,  14.8,  18.4,
        21. ,  12.7,  13.2,  13.1,  13.5,  20. ,  24.7,  30.8,  34.9,
        26.6,  25.3,  21.2,  19.3,  14.4,  19.4,  19.7,  20.5,  25. ,
        23.4,  35.4,  31.6,  23.3,  18.7,  16. ,  22.2,  33. ,  23.5,
        22. ,  17.4,  20.9,  24.2,  22.8,  24.1,  21.4,  20.8,  20.3,
        28. ,  23.9,  24.8,  22.5,  23.6,  22.6,  20.6,  28.4,  38.7,
        43.8,  33.2,  27.5,  26.5,  18.6,  20.1,  19.5,  19.8,  18.8,
        18.5,  18.3,  19.2,  17.3,  15.7,  16.2,  18. ,  14.3,  23. ,
        18.1,  17.1,  13.3,  17.8,  14. ,  13.4,  11.8,  13.8,  14.6,
        15.4,  21.5,  15.3,  17. ,  41.3,  24.3,  27. ,  50. ,  22.7,
        23.8,  22.3,  19.1,  29.4,  23.2,  24.6,  29.9,  37.2,  39.8,
        37.9,  32.5,  26.4,  29.6,  32. ,  29.8,  37. ,  30.5,  36.4,
        31.1,  29.1,

In [41]:
linear.fit(attributes, labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

Getting linear coeficients

In [42]:
linear.coef_

array([  2.09281375e-01,   1.49403979e-02,   1.27164577e-02,
         3.00565375e+00,  -1.55234852e+01,   4.29955958e+00,
         2.84848139e-03,  -1.08366345e+00,   1.93258621e-01,
        -2.42034372e-03,  -9.65535221e-01,   9.43510233e-03,
        -5.25242783e-01])

In [43]:
regularized.fit(attributes, labels)

ElasticNet(alpha=10, copy_X=True, fit_intercept=True, l1_ratio=0.1,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [44]:
regularized.coef_

array([ 0.        ,  0.04662724, -0.02215707,  0.        , -0.        ,
        0.09519651,  0.03318902, -0.06521052,  0.        , -0.00743636,
       -0.23847899,  0.00793473, -0.66007712])

We have a siplier model as an output

We can test by changing weight and attributes parameters

In [46]:
regularized2 = ElasticNet(alpha = 20, l1_ratio = 2)
regularized2.fit(attributes, labels)
regularized2.coef_

array([ 0.        ,  0.01378854, -0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.02090492,
        0.        ,  0.01114263, -0.        ])