In [14]:
%matplotlib inline
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, LogisticRegression, ElasticNet, Lasso, Ridge

In [2]:
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header=None)

In [4]:
iris.columns = ["sepal length", "sepap width", "petal length", "petal width", "class"]

iris.head()

sepal length  sepap width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
iris_labels = iris["class"]
iris_labels.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [11]:
iris_attributes = iris.drop("class", axis = 1)
iris_attributes.head()

sepal length  sepap width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [15]:
model = LogisticRegression(C = 1000)
model.fit(iris_attributes, iris_labels)

LogisticRegression(C=1000, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

An additional model with different regularization

In [16]:
model2 = LogisticRegression(C = 0.001)
model2.fit(iris_attributes, iris_labels)

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

Comparing the coeficients

In [18]:
print(model.coef_)
print(model2.coef_)

[[  1.23447535   4.11821962  -6.5325072   -3.18715121]
 [ -0.24642288  -2.77165187   1.29541375  -2.69962978]
 [ -2.74173879  -5.43038356   7.64430754  14.01832527]]
[[-0.04348189  0.01262464 -0.10492563 -0.04312338]
 [-0.04640808 -0.04148572 -0.00621299 -0.00336127]
 [-0.04749163 -0.04712036  0.03258157  0.02282612]]
